#### general settings
name: DP_38_R85_W1_C_DF2K
use_tb_logger: True
model: sr
distortion: sr
scale: 4
save_img: True
gpu_ids: [8,9]

#### datasets
datasets:
  train:
    name: DF2K
    mode: LQGT
    dataroot_GT: /data2/zy42/PAN_data/hr
    dataroot_LQ: /data2/zy42/PAN_data/x4
    
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    GT_size: 256
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGT
    dataroot_GT: ../datasets/Urban100/HR
    dataroot_LQ: ../datasets/Urban100/LR_bicubic/X4

#### network structures
network_G:
  which_model_G: PAN
  in_nc: 3
  out_nc: 3
  nf: 40
  unf: 24
  nb: 16
  scale: 4
  
#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 7e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3
  #### dynamic precision related 
  DP: True 
  prec_opt: sgd 
  prec_lr: 1.0
  fix_bit: ~  
  max_bit: 8
  min_bit: 3 
  change: True # change flops weight 
  target_ratio: 0.85 
  loss_flops_weight: 1
  calc_bp_cost: True  # calculate bp cost when computing efficiency metric 
  loss_type: thres # in [rela, thres] 
  grad_bit: 16
  tb_logging_interval: 10



#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
