#### general settings
name: DP_816_R8
use_tb_logger: True
model: sr
distortion: sr
scale: 4
save_img: True
gpu_ids: [6,7]

#### datasets
datasets:
  train:
    name: DF2K
    mode: LQGT
    dataroot_GT: /home/zy42/dataset/PAN_data/PAN_data/hr
    dataroot_LQ: /home/zy42/dataset/PAN_data/PAN_data/x4
    
    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 256
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Urban100
    mode: LQGT
    dataroot_GT: /home/zy42/dataset/Urban100/HR
    dataroot_LQ: /home/zy42/dataset/Urban100/LR_bicubic/X4

#### network structures
network_G:
  which_model_G: PAN
  in_nc: 3
  out_nc: 3
  nf: 40
  unf: 24
  nb: 16
  scale: 4
  
#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 7e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
#  niter: 1000000
  niter: 500000
  warmup_iter: -1  # no warm up
#  T_period: [250000, 250000, 250000, 250000]
  T_period: [250000, 250000]
#  restarts: [250000, 500000, 750000]
  restarts: [250000]
#  restart_weights: [1, 1, 1]
  restart_weights: [1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3
  #### dynamic precision related 
  DP: True
  prec_opt: sgd 
  prec_lr: 0.1
  fix_bit: ~ 
  max_bit: 16
  min_bit: 8 
  change: False # change flops weight 
  target_ratio: 0.8
  loss_flops_weight: 1
  calc_bp_cost: False  # calculate bp cost when computing efficiency metric 
  loss_type: thres # in [rela, thres] 
  grad_bit: 16
  tb_logging_interval: 100
  reference: 'prec_grad'



#### logger
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e4
